// Canonical Telegram command menu — shared by setup (setMyCommands) and docs.
// Descriptions must stay <= 100 chars (Bot API limit).
export const COMMANDS = [
  ["start", "Welcome + full command list"],
  ["help", "Full command list"],
  ["status", "Session, model, dir"],
  ["new", "Fresh session (resets context)"],
  ["sessions", "Sessions by name"],
  ["use", "Switch: /use number or name"],
  ["messages", "Last messages + IDs"],
  ["abort", "Stop the running task"],
  ["share", "Public link for session"],
  ["fork", "Branch current session"],
  ["summarize", "Summarize session"],
  ["undo", "Revert a message"],
  ["diff", "Files changed this session"],
  ["todo", "Session todo list"],
  ["export", "Export session JSON"],
  ["model", "Set model: provider/model"],
  ["agent", "Set agent"],
  ["models", "List models"],
  ["providers", "List providers"],
  ["agents", "List agents"],
  ["commands", "OpenCode slash commands"],
  ["tools", "All available tools"],
  ["mcp", "MCP server status"],
  ["lspstatus", "LSP status"],
  ["config", "OpenCode config"],
  ["health", "Server health"],
  ["stats", "Token/cost stats"],
  ["bash", "Run shell via opencode"],
  ["shell", "Session shell (logged)"],
  ["read", "Read a file (no LLM cost)"],
  ["edit", "Guided edit: path :: old :: new"],
  ["write", "Guided write: path :: content"],
  ["grep", "Search code (no LLM cost)"],
  ["find", "Search code alias"],
  ["glob", "Find files by pattern"],
  ["ls", "List files"],
  ["webfetch", "Fetch a URL"],
  ["websearch", "Search the web"],
  ["skill", "Load a skill"],
  ["todoadd", "Add a todo"],
  ["lsp", "Code intelligence"],
  ["ask", "Have opencode question you"],
  ["cli", "Raw opencode passthrough"],
  ["run", "One-shot agent run"],
  ["allow", "Approve a permission"],
  ["deny", "Reject a permission"],
];
